### ISSUE TITLE
如何基于CircleLayoutManager实现椭圆圆弧的效果呢

### ISSUE THREAD

**Issue by cxMax** [leochuan/ViewPagerLayoutManager#103]
RT， 有同样需求的小伙伴吗？

**Comment by cxMax** [comment]
一直没看懂， CircleLayoutManager里面calItemLeft()、calItemTop()里面弧度的计算是怎么一个逻辑。
例如 :
(int) (radius * Math.cos(Math.toRadians(90 - targetOffset)));
(int) (radius - radius * Math.sin(Math.toRadians(90 - targetOffset)));

有领悟了的同学吗？ 请问， 万分感谢

**Comment by cxMax** [comment]
领悟了一波，暂时关闭。 不过里面的计算相关的代码还是没有完全搞懂

**Comment by spd-heshuip** [comment]
@cxMax 老哥，你领悟calItemLeft()，calItemTop()的逻辑吗？

**Comment by spd-heshuip** [comment]
@cxMax 老哥，基于CircleLayoutManager实现椭圆圆弧的效果你实现了吗？

**Comment by cxMax** [comment]
@spd-heshuip 没有，我看了下之前弧度的提交。并没有改成功。
