### ISSUE TITLE
ElevateScaleLayoutManager elevation issue!?

### ISSUE THREAD

**Issue by SIMMORSAL** [leochuan/ViewPagerLayoutManager#14]
hi, im using ElevateScaleLayoutManager, and it works perfectly fine on android 5+, but on below that i have a problem with elevation (i think), and by that i mean the views on right are always drawn over the views on their left. is there any fix for it?

**Comment by leochuan** [comment]
Hi, @SIMMORSAL . ElevateScaleLayoutManager internally use `setElevation` to handle elevation which only works above api21. But I am considering reconstruct this library recently. So maybe it will be fixed in next release.

**Comment by SIMMORSAL** [comment]
thanks for the reply. i tried replacing setElevation with ViewCompat.setElevation (and commenting the api check if statement), but again it doesn't work on api 17. do you have any quick fix for it in mind? my customer likes your library, and is eating my brain to fix it!

**Comment by leochuan** [comment]
Sorry I can not figure out any quick fix either...But I will fix it in this week.

**Comment by leochuan** [comment]
@SIMMORSAL you can try the new version.. I fixed a bunch of bugs and it supports elevation below api 21 now

**Comment by SIMMORSAL** [comment]
Thanks. I will definitely give it a try.
