### ISSUE TITLE
ScaleLayoutManager这个不支持Recyclerview的不同类型吗？

### ISSUE THREAD

**Issue by zhanghangcode** [leochuan/ViewPagerLayoutManager#15]
你好，这里我用了两种类型来显示，但是总是什么都显示不出来。

**Comment by leochuan** [comment]
@zhanghangcode 我最近在更新这个库，改了很多东西，之前有很多问题，先别用。大概明天会发个新版本

**Comment by zhanghangcode** [comment]
谢谢你的回复，我看到你的库已经更新了，但是我这边现在有一个新的需求，我发现自定义的这个ViewPagerLayoutMagager管理类，没有LinearLayoutManager里面的两个方法findFirstVisibleItemPosition()和findLastVisibleItemPosition。用来获取当前的item。因为我需要在Recyclerview里面添加两种类型的type，一种为图片，另外一种为视频。当滑动到视频的item的时候让视频自动播放。




在 2017-10-31 19:44:23，"leo shen" <notifications@github.com> 写道：


@zhanghangcode 我最近在更新这个库，改了很多东西，之前有很多问题，先别用。大概明天会发个新版本

**Comment by leochuan** [comment]
给`recyclerView`添加 `CenterScrollListener `

**Comment by zhanghangcode** [comment]
谢谢你的回复，可以认识一下吗？加一下你的微信。有什么问题方便请教你






在 2017-11-16 11:24:38，"leo shen" <notifications@github.com> 写道：


给recyclerView添加 CenterScrollListener

**Comment by leochuan** [comment]
可以加下qq, 378534547
