### ISSUE TITLE
在DialogFragment里 item宽度显示问题

### ISSUE THREAD

**Issue by spysoos** [leochuan/ViewPagerLayoutManager#16]
在DialogFragment里 RecyclerView item宽度设置match_parent 但是在显示时并没有占满父View 望修复

**Comment by spysoos** [comment]
不知道怎么贴图
[http://ys-f.ys168.com/383712285/nxsSwvk2J76534U7L36/TIM%E6%88%AA%E5%9B%BE20171121092606.png]效果图

**Comment by leochuan** [comment]
@spysoos 方便的话，把你`recyclerView`所在的xml贴上来看看

**Comment by leochuan** [comment]
我自己试了下，在`DialogFragment`里给`item`宽度设置为`match_parent`，并没有出现你说的这种情况，最好可以给我看下你的布局文件，这样可以让我比较快速的定位问题

**Comment by spysoos** [comment]
不好意思，忘记start，好不容易找回这里。

以下是DialogFragment的布局：

`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_gravity="center"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:minWidth="400dp"
    android:orientation="vertical">

    <android.support.v7.widget.RecyclerView
        android:id="@+id/content_rv"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scrollbars="none"
        android:overScrollMode="never"
        tools:listitem="@layout/item_text"/>

    <LinearLayout
        android:id="@+id/option_panel"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal"
        android:visibility="visible">

        <Button
            android:layout_width="0dp"
            android:layout_height="40dp"
            android:layout_weight="1"
            android:background="@android:color/black"
            android:gravity="center"
            android:orientation="horizontal"
            android:text="取消"
            android:textColor="#ffffff"/>

        <Button
            android:layout_width="0dp"
            android:layout_height="40dp"
            android:layout_weight="1"
            android:background="@android:color/black"
            android:gravity="center"
            android:orientation="horizontal"
            android:text="确认"
            android:textColor="#ffffff"/>
    </LinearLayout>

</LinearLayout>`

这是Item的布局：
`<?xml version="1.0" encoding="utf-8" ?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="48dp">

    <TextView
        android:id="@+id/content"
        android:textSize="15sp"
        android:gravity="center"
        android:textColor="#353535"
        android:lines="1"
        tools:text="2017"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>
</FrameLayout>`

这是DialogFragment的源码：
`public class Dialog extends DialogFragment {

    public static Dialog newInstance() {
        Bundle bundle = new Bundle();
        Dialog dialog = new Dialog();
        dialog.setArguments(bundle);
        return dialog;
    }

    @Nullable @Override public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.view_dialog_date, container);
        RecyclerView recyclerView = view.findViewById(R.id.content_rv);
        ScaleLayoutManager scaleLayoutManager = new ScaleLayoutManager(10);
        scaleLayoutManager.setOrientation(ViewPagerLayoutManager.VERTICAL);
        recyclerView.setAdapter(new DataAdapter2());
        recyclerView.setLayoutManager(scaleLayoutManager);

        return view;
    }

}
`
适配器：
`public class DataAdapter2 extends RecyclerView.Adapter<DataAdapter2.ViewHolder> {
    private String[] images = {"2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017"};

    @Override
    public DataAdapter2.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        return new ViewHolder(LayoutInflater.from(parent.getContext()).inflate(R.layout.item_text, parent, false));
    }

    @Override
    public void onBindViewHolder(DataAdapter2.ViewHolder holder, int position) {
        holder.tvView.setText(images[position]);
        holder.tvView.setTag(position);
    }

    @Override
    public int getItemCount() {
        return images.length;
    }

    class ViewHolder extends RecyclerView.ViewHolder {
        TextView tvView;

        ViewHolder(View itemView) {
            super(itemView);
            tvView = (TextView) itemView.findViewById(R.id.content);
            tvView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    Toast.makeText(v.getContext(), "clicked:" + v.getTag(), Toast.LENGTH_SHORT).show();
                }
            });
        }
    }
}
`

![tim 20171129171617](https://user-images.githubusercontent.com/982866/33367315-0ca36abc-d529-11e7-8f39-b70e2357baa3.png)

**Comment by spysoos** [comment]
如果可以 可以留下邮箱 我发工程给你

**Comment by leochuan** [comment]
@spysoos 这个问题可能我暂时解决不掉， `LayoutManager` 有一个 `shouldMeasureTwice`方法是`package`作用域的，我不能覆写他，这个方法的作用是在子view大小不确定的时候再次测量的。注释上说不能复写的原因是会在未来重构的时候移除他。而让`ViewpagerLayoutManager`继承`LinearLayoutManager`的话改动会比较大，所以我的建议是你设置一下`DialogFragment`的大小，然后给`item`的宽高设置一个固定的值。

**Comment by spysoos** [comment]
@leochuan 目前我也是设固定值解决的，其他都很OK，3Q

**Comment by leochuan** [comment]
@spysoos 我想了想，还是改成继承自LinearLayoutManager了。看效果上好像没什么问题，我看看没别的问题应该会更新一下

**Comment by leochuan** [comment]
Fix by commit: 153e0a6c5db0141fe1599d13708a8154d8243b76
好了，更新了，建议等新版上传好之后用新的版本，如果有用到无限滚动的话
