### ISSUE TITLE
ScaleLayout图片为3个时，循环轮播会产生一个空白页

### ISSUE THREAD

**Issue by shenghou123** [leochuan/ViewPagerLayoutManager#17]
ScaleLayout图片为3个时，循环轮播会产生一个空白页，

**Comment by leochuan** [comment]
@shenghou123 thx, 过几天和其它几个小问题一起修复了发个新版本

**Comment by leochuan** [comment]
fix by commit: 9dd65d712996baccbcd5f024b68b3f6c69343b65
好了, 修复了
