### ISSUE TITLE
如何做到前一个Item部分叠加在后一个Item上的效果呢？

### ISSUE THREAD

**Issue by SunGuangjie** [leochuan/ViewPagerLayoutManager#18]

**Comment by leochuan** [comment]
@SunGuangjie 哪一种`layoutmanager`?

**Comment by SunGuangjie** [comment]
CircleScaleLayoutManager在初始状态时的展现形式，是怎样做到前一个Item叠加在后一个Item上的呢？

**Comment by leochuan** [comment]
@SunGuangjie 当初写这个的时候定的是越中间的 `view` z轴越高，如果你确实需要从左往右或者从右往左盖上去的话，我可以提供一下支持，之后可能也会把定义z轴的方法暴露出来

**Comment by SunGuangjie** [comment]
类似下图这种效果,5.0之前没有setElevation方法，Z轴没有思路了
![image](https://github.com/SunGuangjie/SplitScrollNumberView/blob/master/app/gif/Paste%20Image.png)

**Comment by leochuan** [comment]
最晚后天， 我会更新一个版本

**Comment by leochuan** [comment]
噗，好在赶在12点之前更新了，`CSLM` 新增了一个 `setZAlignment`方法 支持三种参数`CircleScaleLayoutManager.LEFT_ON_TOP`、`CircleScaleLayoutManager.RIGHT_ON_TOP`、`CircleScaleLayoutManager.CENTER_ON_TOP`

**Comment by leochuan** [comment]
Fix buy commit: 153e0a6c5db0141fe1599d13708a8154d8243b76

**Comment by SunGuangjie** [comment]
多谢啦。
