### ISSUE TITLE
请问可以设置滑动卡片可见个数吗？

### ISSUE THREAD

**Issue by yuyu06** [leochuan/ViewPagerLayoutManager#19]
比如我只想显示3个，滑动过后出现后续的卡片，但是每次只能看到3个卡片

**Comment by leochuan** [comment]
@yuyu06 目前还没有直接设置可见个数的api， 不过像弧形滚动的两个`layoutManager`有`setMinRemoveAngle` 以及 `setMaxRemoveAngle` 这两个api可以设置范围，其它的`layoutManager`也可以通过继承后重写`maxRemoveOffset `和`minRemoveOffset `实现。不过我觉得你这个建议还不错，不着急的话我明后天会更新一下这个功能

**Comment by leochuan** [comment]
好了， fix by commit: d5ea494

**Comment by yuyu06** [comment]
谢谢
