### ISSUE TITLE
请问可以改变圆心为之么？

### ISSUE THREAD

**Issue by ilittle7** [leochuan/ViewPagerLayoutManager#20]
CircleLayoutManager，是以底部为圆心，可以以左边为圆心么，滑动路径是这个形状的“  ）”

**Comment by leochuan** [comment]
当时我有思考过这个问题，要不要让他支持4个方向。你确定你要的效果是这种每一个`item`中线都是贯穿圆心的？ 还是说其实每个`view`自身不旋转，但是围绕圆心形成一个圈？ 这是两种不同的`layoutManager`，如果是后一种的话我准备加一个这样子的效果然后他是支持四种朝向的。前一种的话，你真的有这种需求，我也可以支持一下，目前是不支持的。

**Comment by ilittle7** [comment]
我说的就比如是这种，这样圆心不就是在左边了么，Demo中圆心是在下边的
您可以支持改变圆心位置么？

**Comment by ilittle7** [comment]
大神，可以变成这样么？

**Comment by leochuan** [comment]
@ilittle7 看不到你的图片啊，我这两天公司事情比较多，应该过几天更新一下。

**Comment by ilittle7** [comment]
辛苦辛苦，就是这个意思，圆形的旋转效果那个，把recyclerview向右旋转90度的效果。


| |
历建斌
|
|
邮箱：ilittle7@163.com
|

签名由 网易邮箱大师 定制

在2017年12月07日 18:48，leo shen 写道：

@ilittle7 看不到你的图片啊，我这两天公司事情比较多，应该过几天更新一下。

**Comment by leochuan** [comment]
@ilittle7 
好了，现在可以传一个`Gravity`，参数是`CircleLayoutManager.LEFT`、`CircleLayoutManager.RIGHT`、`CircleLayoutManager.TOP`、`CircleLayoutManager.BOTTOM`

commit: 5ecc4c80a26e7731f3054092dc5b35fbf4751f64
