### ISSUE TITLE
List item gets lost in infinite scroll

### ISSUE THREAD

**Issue by jasonMisaq** [leochuan/ViewPagerLayoutManager#22]
Hi
I am using CarouselLayoutManager to create a carousel list of items. In a small list with a few items, when set to infinite scroll, after the first round, one of the items gets hidden! What does cause this?

**Comment by leochuan** [comment]
Hi @jasonMisaq. Someone had reported this issue for version `2.0.0`. And I fixed it in `2.0.1` by 9dd65d7. Are you using version `2.0.1`?

**Comment by jasonMisaq** [comment]
@leochuan  I upgraded to 2.0.1 and now it works fine. Thanks
