### ISSUE TITLE
How to prevent auto duplication of list items in infinite scroll mode

### ISSUE THREAD

**Issue by jasonMisaq** [leochuan/ViewPagerLayoutManager#24]
When I set my list to infinite scroll mode using `mLayoutManager.setInfinite(true);`, the library seems to auto duplicate items to fill the screen if there are only a few items (like two or three) in the list. How can I prevent this from happening. What should I do if I want to see only the items I have set in the list even if there is only 1 or 2 items, while still being able to scroll them infinitely?

**Comment by leochuan** [comment]
When enable `setInfinite`, It should be able to scroll in both direction. So I don't think it could work when size is smaller than 3. All I can do is offer an api which sets the max visible item count.

**Comment by leochuan** [comment]
fix by commit: d5ea4946eaac1ef3de847bf656812400ae00de95
I added a method called `setMaxVisibleItemCount(int count)`, You can set the size as max visible item count, I think this can solve your problem. And this feature will be included in next release.

**Comment by jasonMisaq** [comment]
@leochuan  thanks that's a cool feature.
