### ISSUE TITLE
How to prevent quickly scroll to last item?

### ISSUE THREAD

**Issue by Kolyall** [leochuan/ViewPagerLayoutManager#28]
If you scroll default recyclerView, then it scrolling with gradual deceleration of speed.
But if I scroll recyclerView with this settings:
```
mRecyclerView.setLayoutManager(new ScaleLayoutManager(getActivity(),0));
(new LinearSnapHelper()).attachToRecyclerView(mRecyclerView);
```
then it scrolling with constant speed till to last item. How to prevent it?

**Comment by leochuan** [comment]
if you just want to center the item, I suggest `recyclerView.addOnScrollListener(new CenterScrollListener());` instead of using `LinearSnapHelper `

**Comment by leochuan** [comment]
@Kolyall try version `2.0.6` and use `new CenterSnapHelper().attachToRecyclerView(mRecyclerView)` it's more smooth.. and work exactly same as `LinearSnapHelper `
