### ISSUE TITLE
item 宽度问题

### ISSUE THREAD

**Issue by wenchaosong** [leochuan/ViewPagerLayoutManager#30]
用 ScaleLayoutManager 的话，item 不能设置 match_parent，必须要设置固定的宽度
这样会带来适配的问题
能不能改成 margin 或者 padding，就不用设置固定的宽度

**Comment by leochuan** [comment]
现在可以match_parent的吧，只是要求你每一个item大小必须一样

**Comment by wenchaosong** [comment]
用 match_parent 会占满整个屏幕的宽度，左右2边的 item 显示不了，要滑动才看得到
设置固定的宽度，左右2边的 item 才会显示出来

**Comment by leochuan** [comment]
match_parent当然会占满整个屏幕...如果你是说要滑动比较大的距离，才会显示的话你设置一下`setMaxVisibleItemCount(3)`这样就好了，不然你是想要显示三个item的话肯定不能用match_parent，可以拿到屏幕宽度，除以3自己设置一下item大小

**Comment by wenchaosong** [comment]
match_parent 是会占满整个屏幕，但是
配合 ScaleLayoutManager 一起用的话，占满屏幕就没有意义了

我的意思是对外提供一个接口，用来设置这个距离

比如在这之前引用了 viewpager 来做这个需求，它就是通过设置 param 控制2端缩进距离，
不过存在白屏的问题就没用

**Comment by leochuan** [comment]
@wenchaosong 好了，用`2.0.5`新增了一个api `setShrinkSpace(int shrinkSpace)`，会在当前宽度的基础上左右各收缩这个宽度。

**Comment by wenchaosong** [comment]
刚试了一下，就是这个意思，毕竟安卓还有个适配的问题，不能因为解决其他问题带来新的问题

给个赞

**Comment by leochuan** [comment]
其实你自己拿到`recyclerView`的宽度，两边减去一个固定的值再设成item的宽度，达到的效果是一样的，我思考了下觉得确实有这种场景提供个api可能方便一点才决定加上的。自动轮播的话，还是自己设定时器让`recyclerView`滚动到特定位置吧，`layoutmanager`只是负责`recyclerView`如何排列展示他的item而已

**Comment by tpnet** [comment]
@leochuan  为什么最新版没有shrinkSpace设置了？？？

**Comment by leochuan** [comment]
@tpnet 因为这个属性的场景仅限于match_parent的时候缩进一下，我内部为了实现这个东西加了很多额外的操作，然而这些操作对于其他场景下是多余的，所以后来考虑了下还是去掉了，由外部自己设置。

**Comment by tpnet** [comment]
@leochuan  外部 在哪个地方设置呢？

**Comment by leochuan** [comment]
@tpnet 可以在ViewHolder的构造方法里面设置一下itemView的宽度

**Comment by tpnet** [comment]
@leochuan  可以了，牛批，谢谢大佬
