### ISSUE TITLE
请问 CircleScaleLayoutManager 怎么设置底部为旋转圆心

### ISSUE THREAD

**Issue by yuyu06** [leochuan/ViewPagerLayoutManager#31]

**Comment by leochuan** [comment]
默认不就是底部的吗？？

**Comment by yuyu06** [comment]
设置gravity为水平，旋转中心是左侧，为垂直，旋转中心却变成右侧。。。

**Comment by leochuan** [comment]
额，我知道为啥了= = `HORIZONTAL = 0` `VERTICAL = 1` 
然后其实 `gravity` 的参数是`LEFT = 0` `RIGHT = 1` `TOP = 2` `BOTTOM = 3`

我其实是做了报错了= =。。我把数字改成不一样的好了
```java
private static void assertGravity(int gravity) {
    if (gravity != LEFT && gravity != RIGHT && gravity != TOP && gravity != BOTTOM) {
        throw new IllegalArgumentException("gravity must be one of LEFT RIGHT TOP and BOTTOM");
    }
}
```

**Comment by yuyu06** [comment]
所以现在可以直接使用HORIZONTAL了吗（之前有事没在工作）

**Comment by leochuan** [comment]
不是啊 `HORIZONTAL` 和 `VERTICLE` 不是用于`gravity`的，你要圆心在底部的话 设置`gravity`为`BOTTOM`, 或者直接不设默认就是底部

**Comment by yuyu06** [comment]
感谢了。

**Comment by leochuan** [comment]
嗯, 这个确实可以有，之后版本加一下。

**Comment by yuyu06** [comment]
请问是否可以实现卡片层叠方向与滑动方向不一样。比如层叠方向是垂直，滑动是水平
