### ISSUE TITLE
Items cannot be navigated after several loops

### ISSUE THREAD

**Issue by djnotes** [leochuan/ViewPagerLayoutManager#32]
I am navigating the items via Keyboard (on emulator) or Android TV via D-Pad, and the navigation seems to work after several rounds for infinite lists. How can I fix that?

**Comment by leochuan** [comment]
Could you be more specific ?? I tried about hundred of times it still work fine.  Did you pressed the `ok` button to see which one gets focused

**Comment by jasonMisaq** [comment]
After about 8 loops that you scroll the items forward or backward, the scroll stops. It seems that disabling infinite scroll solves this and then you can scroll as many times as you want end to end.

**Comment by jasonMisaq** [comment]
This seems to happen only for the my main list with three items. Others are fine. I have a hidden floating action button on the same activity (with a  root of CoordinatorLayout). Can this be the reason why navigation gets lost? And by the way, I have set these attributes for my list item root layouts:   
``
focusable="true" 
background="@drawable/selector"
``

**Comment by leochuan** [comment]
@jasonMisaq I find it will stop at position `-getItemCount()` every time, then I find `getCurrentPosition` of `-getItemCount()` it returned `getItemCount()` instead of `0`.
You could try version `2.0.8` later. I just fix that.

**Comment by jasonMisaq** [comment]
The app does not compile with the new version. I get the following errors:  
```
Error:(15, 20) error: package com.leochuan does not exist
Error:(16, 20) error: package com.leochuan does not exist
Error:(31, 13) error: cannot find symbol class CarouselLayoutManager
Error:(61, 13) error: cannot find symbol class CarouselLayoutManager
/home/johndoe/src/ZoodVideo/app/src/main/java/com/zood/mediaplayer/MusicListActivity.java
Error:(18, 20) error: package com.leochuan does not exist
Error:(19, 20) error: package com.leochuan does not exist
Error:(32, 13) error: cannot find symbol class CarouselLayoutManager
Error:(57, 13) error: cannot find symbol class CarouselLayoutManager
/home/johndoe/src/ZoodVideo/app/src/main/java/com/zood/mediaplayer/VideoListActivity.java
Error:(22, 20) error: package com.leochuan does not exist
Error:(23, 20) error: package com.leochuan does not exist
Error:(64, 13) error: cannot find symbol class CarouselLayoutManager
/home/johndoe/src/ZoodVideo/app/src/main/java/com/zood/mediaplayer/LibraryActivity.java
Error:(15, 20) error: package com.leochuan does not exist
Error:(16, 20) error: package com.leochuan does not exist
Error:(32, 13) error: cannot find symbol class CarouselLayoutManager
Error:(59, 13) error: cannot find symbol class CarouselLayoutManager
/home/johndoe/src/ZoodVideo/app/src/main/java/com/zood/mediaplayer/FilmGroupActivity.java
Error:(14, 20) error: package com.leochuan does not exist
Error:(15, 20) error: package com.leochuan does not exist
Error:(27, 13) error: cannot find symbol class CarouselLayoutManager
Error:(58, 15) error: cannot find symbol class CarouselLayoutManager
/home/johndoe/src/ZoodVideo/app/src/main/java/com/zood/mediaplayer/MainGroupActivity.java
Error:(15, 20) error: package com.leochuan does not exist
Error:(16, 20) error: package com.leochuan does not exist
Error:(17, 20) error: package com.leochuan does not exist
Error:(26, 13) error: cannot find symbol class CarouselLayoutManager
Error:(86, 15) error: cannot find symbol class CarouselLayoutManager
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED in 1s
Information:25 errors
Information:0 warnings
Information:See complete output in console
```
Cleaning and rebuilding the project did not work.

**Comment by leochuan** [comment]
Cause it haven't been uploaded.. I think it's done now.

**Comment by jasonMisaq** [comment]
Still got the errors!

**Comment by leochuan** [comment]
Try to delete the gradle cache and re-sync the project.
If you use osx it may store at `~/.gradle/caches/modules-2/files-2.1/rouchuan.viewpagerlayoutmanager/viewpagerlayoutmanager`
