### ISSUE TITLE
Can VPLM Arrange the Items Evenly on the Screen?

### ISSUE THREAD

**Issue by djnotes** [leochuan/ViewPagerLayoutManager#33]
Can VPLM automatically arrange the lists items on screen so that they look asymmetrical and not biased. To put it simply, for example, I have three items, then VPLM should scroll to item 1 (second item) and not item 0 (1st item). If I have only one item, then the item should be centered by default, and so on.    
#### I want this:  

! [Desired ]   
(https://ibb.co/n5AqsG)

#### But, I see this:  

! [Bad]   
(https://ibb.co/hXVemb)

**Comment by leochuan** [comment]
You can use `RecyclerView`'s `scrollToPosition` or `SmoothScrollToPosition` to scroll to position 1 at the first beginning. And if there is less than 3 items, you do not scroll it.
