### ISSUE TITLE
The lists seem to need two swipes to scroll on phone

### ISSUE THREAD

**Issue by djnotes** [leochuan/ViewPagerLayoutManager#34]
Hi 
The list navigation works perfect with D-Pad on Android TV (MXQ-4K), however, it seems that scrolling the list now requires two swipes and selecting an item needs two taps! I confirm this for a real phone and an emulated device.  Can this be an issue with VPLM?

**Comment by leochuan** [comment]
You could use a default `LayoutManager` like `LinearLayoutManager` to see if it is still need twice swipe. If it does then it's nothing to do with `VPLM`. If it does not, then try not to use  `CenterSnapHelper` and check it again. Cause it works fine in my demo, I need you to narrow the possible to help me locating the issue.

**Comment by djnotes** [comment]
I found the issue was caused by the following code in my BaseActivity. I use that to keep the navigation bar hidden all the time. That's because this is a kiosk-like application and the navigation bar does not need to be seen.   
```
final View decorView = getWindow().getDecorView();
        int uiOptions = View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION;
        decorView.setSystemUiVisibility(uiOptions);

        //Set a system bar visibility change listener
        decorView.setOnSystemUiVisibilityChangeListener(
                new View.OnSystemUiVisibilityChangeListener() {
                    @Override
                    public void onSystemUiVisibilityChange(int visibility) {
                        if ((visibility & View.SYSTEM_UI_FLAG_FULLSCREEN) == 0) {
                            decorView.setSystemUiVisibility(
                                    View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                                            | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION);
                        }
                    }
                }
        );

```  
When I remove this code, the swipe works fine. But, I don't know what to use instead to hide the navigation bar.

**Comment by leochuan** [comment]
see [Using Immersive Full-Screen Mode](https://developer.android.com/training/system-ui/immersive.html) 
```java
final View decorView = getWindow().getDecorView();
int uiOptions = View.SYSTEM_UI_FLAG_IMMERSIVE | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION;
decorView.setSystemUiVisibility(uiOptions);
```

**Comment by djnotes** [comment]
Thanks.
