### ISSUE TITLE
D-Pad jumps over the items when navigating with remote controller D-Pad

### ISSUE THREAD

**Issue by djnotes** [leochuan/ViewPagerLayoutManager#35]
I noticed that when the system language is set to the Persian (RTL) locale, navigating the items with D-Pad (on remote controller) is wrong. For example you press right on the remote and the list jumps to a random item (not the next). It seems this is only true for android TV (remote controller D-Pad). Testing with keyboard on an emulator device with the Persian locale does not seem to have the problem. Can you please the issue? Is the library dependent on LTR locales to work?

**Comment by djnotes** [comment]
It would be good if the items in the list work consistently in all locales. Currently, **it seems it only works well with English**.

**Comment by leochuan** [comment]
It works fine on my emulator, cause I don't have a real android TV..I can't debug...Maybe you can debug it for me and request a PR.

**Comment by djnotes** [comment]
Sure. I'm not a professional but I'll do my best. Currently, I am running your demo app on TV emulator (which only has English). First it works fine, but when I switch on the "infinite" option, it cannot navigate the items with keyboard directions anymore (confirmed on TV emulators API 23 and 26). I will run  your app APK on the real TV device and get back to you also.

**Comment by djnotes** [comment]
Please see this video which shows the app running on  Android TV Box: MXQ-4K: 
https://youtu.be/ac4_dVtR77g

**Comment by leochuan** [comment]
thx, the first issue you can try version `2.0.9` until `Download tag` in homepage become `2.0.9`..But I am not sure if I fixed it..check it for me.

the second issue about my demo app, it is nothing to do with infinite, after you pressing `up` on your remote to select the setting button, you need to press 'down' to make `recyclerView` get focus again

**Comment by djnotes** [comment]
Thanks for the fix I will check and get back to you ASAP. 
Sent from Yahoo Mail on Android 
 
  On Thu, Jan 4, 2018 at 7:40 PM, leo shen<notifications@github.com> wrote:   
thx, the first issue you can try version 2.0.9 until Download tag in homepage become 2.0.9..But I am not sure if I fixed it..check it for me.

the second issue about my demo app, it is nothing to do with infinite, after you pressing up on your remote to select the setting button, you need to press 'down' to make recyclerView get focus again

**Comment by djnotes** [comment]
The 2.0.9 release works perfectly with the emulator in RTL mode 👍  No more wrong jumps over the items. I'll also test on the TV device at the earliest time and report back if there are any issues.
