### ISSUE TITLE
有个问题

### ISSUE THREAD

**Issue by wenchaosong** [leochuan/ViewPagerLayoutManager#36]
我看你已经弄了 自动滚动的，为什么没把 start stop 方法暴露出来
  
而且自动轮播的东西 bug 最多了，现在你加的这个，滚动到最后一条数据，下一个数据的滚动就会出现 bug

**Comment by leochuan** [comment]
具体是什么bug呢？ 你确实有需要我可以暴露出来

**Comment by wenchaosong** [comment]
很简单的 bug，就是 currentPosition 计算错误，当滚动到最后一条，下一个 position 应该为 0，你没有处理

然后暴露 start 和 stop 是因为要处理和下拉刷新的冲突，下拉的时候 stop，刷新结束后 start，这个和轮播图的道理一样的，我觉得这个是必须要暴露出来的，还可以在 onresume onpause 中调用

**Comment by leochuan** [comment]
我就问你，你有运行过或者仔细看过源码吗？我真是服了你了大兄弟
