### ISSUE TITLE
item点击失效的问题分析

### ISSUE THREAD

**Issue by meihao199204** [leochuan/ViewPagerLayoutManager#37]
centerSnapHelper关联recyclerview，用carouselLayoutManager.setMoveSpeed((float) 0.25)设置recyclerview的滑动速度后，自动归位会卡顿一下，并且有时item的点击无作用，使用默认的滑动速度不会有上述问题。请帮忙看下！非常感谢！！

**Comment by leochuan** [comment]
不好意思，才看到，这两天工作稍微有点忙，这星期之前应该可以把这个问题给修复掉。

**Comment by leochuan** [comment]
好了，等项目主页download tag变成 `2.0.10`用这个版本就好了
fix by: 5b66cb8b6827ec9d74399f9272f1c8fc1e365f8c

**Comment by meihao199204** [comment]
解决了，非常感谢！！
