### ISSUE TITLE
横向RecyclerView第一个可见item放大呢

### ISSUE THREAD

**Issue by MoMuBai** [leochuan/ViewPagerLayoutManager#41]
一个横向的RecyclerView，然后一行的item个数是不限(不像这里3个)，然后滑动，每次滑到的过程第一个可见位置的item要放大[图片](http://p0sgkjh7x.bkt.clouddn.com/24057A0F-54F5-41DB-9479-FC8B509D1DD4.png)，有没有什么思路呢

**Comment by leochuan** [comment]
我并没有限制一行只显示3个啊，现在就是不限制的。
在 `ViewPagerLayoutManager.java`的第365行
`mSpaceMain = (mOrientationHelper.getTotalSpace() - mDecoratedMeasurement) / 2;`
这个`mSpaceMain`就是第一个`item`的偏移，这边取了屏幕宽度然后减去一个item的宽度之后除以二，所以现在默认是放置在屏幕中央。
你可以实现照着`ScaleLayoutManager`实现自己的`LayoutManager`，然后重写`setUp`方法，在里面修改`mSpaceMain`的值，让第一项放置在屏幕左边就好了。你愿意的话可以抽象一下，提一个PR，不然的话过几天我会加一个`API`让你设置这个偏移

**Comment by MoMuBai** [comment]
偏移这个我看到了，现在是偏移虽然偏移，但是放大的item还是在中间项(要让第一个item执行放大效果)，实际上我第一个问题主要想说的还是这个..

**Comment by leochuan** [comment]
嗯，忘记了，`ScaleLayoutManager`里面的`calculateScale`这个方法，这个是计算item的`scale`，现在是把中心点设成最大的`scale`。

改成这样就好了
```java
/**
     * @param x start positon of the view you want scale
     * @return the scale rate of current scroll mOffset
     */
    private float calculateScale(float x) {
        float deltaX = Math.abs(x - mSpaceMain);
        float diff = 0f;
        if ((mDecoratedMeasurement - deltaX) > 0) diff = mDecoratedMeasurement - deltaX;
        return (centerScale - 1f) / mDecoratedMeasurement * diff + 1;
    }

    @Override
    protected void setUp() {
        mSpaceMain = (int) (mDecoratedMeasurement * (centerScale - 1f) / 2);
    }
```

**Comment by MoMuBai** [comment]
恩  好的 谢谢啦 我去试试

**Comment by wankey** [comment]
请问centerScale这个值是什么？在哪赋值的
