### ISSUE TITLE
我在6.0运行是居中的，7.0就跑上面去了

### ISSUE THREAD

**Issue by CaptainBlackCat** [leochuan/ViewPagerLayoutManager#42]

**Comment by leochuan** [comment]
我自己手机就7.0的= =，同样的代码吗？ 代码贴上来看看

**Comment by CaptainBlackCat** [comment]
<FrameLayout
    android:layout_marginTop="10dp"
    android:layout_width="match_parent"
    android:layout_height="100dp"
    android:layout_below="@+id/tv_equity_explain"
    android:layout_alignParentStart="true">
    <View
        android:id="@+id/line_dark"
        android:layout_width="match_parent"
        android:layout_height="3dp"
        android:layout_gravity="center_vertical"
        android:background="@color/colorDark" />
    <View
        android:id="@+id/line_gold"
        android:layout_gravity="center_vertical"
        android:layout_height="3dp"
        android:background="#e1bd87"
        android:layout_width="230.5dp"
       />
     <android.support.v7.widget.RecyclerView
         android:layout_gravity="center_vertical"
         android:id="@+id/recycler"
         android:layout_width="match_parent"
         android:layout_height="match_parent">
     </android.support.v7.widget.RecyclerView>
</FrameLayout>    把height写死100dp就没事了

**Comment by leochuan** [comment]
fix by: 7bc48e9c4562a95dac11312f5f351cab49e241c1
