### ISSUE TITLE
点击item如何将item移到中间文字？

### ISSUE THREAD

**Issue by vibexie** [leochuan/ViewPagerLayoutManager#43]
点击item如何将item移到中间文字

**Comment by leochuan** [comment]
没懂...描述详细一点

**Comment by vibexie** [comment]
比如一屏显示了5张图，我点击最右边的一张，那这一张如何滑到中间显示

**Comment by vibexie** [comment]
我看你的Demo只有一个onClick事件，找了一会儿还是不知道怎么加上这个需求

**Comment by vibexie** [comment]
大神有没有现成的法子哦，求解

**Comment by vibexie** [comment]
@leochuan 大神有没有现成的法子哦，求解

**Comment by leochuan** [comment]
哦哦，`recyclerView.smoothScrollToPosition(你点击view的position)`

**Comment by vibexie** [comment]
谢谢在线解答
