### ISSUE TITLE
如果可以设置子item可以靠左或者靠右就很棒了

### ISSUE THREAD

**Issue by yuyu06** [leochuan/ViewPagerLayoutManager#44]
![1516239968](https://user-images.githubusercontent.com/22373496/35076623-580ce1fe-fc34-11e7-946b-0b62c19e9743.png)

如图

**Comment by yuyu06** [comment]
应该可以在某个方法中设置列表子item的位置吧

**Comment by leochuan** [comment]
嗯，你可以先参考下issue #41 目前没有直接暴露设置的 api 你可以自己写一个 layout manager 继承你要的那个 layout manager 然后重写setup方法
