### ISSUE TITLE
自动轮播不能在Activity  OnPause的时候取消轮播

### ISSUE THREAD

**Issue by tpnet** [leochuan/ViewPagerLayoutManager#51]
自动轮播不能在Activity  OnPause的时候取消轮播，在onResume的时候恢复轮播。。   这样子的话，界面隐藏了，还会一直发现轮播，对内存消耗有影响。

看了源码，好像在AutoPlaySnapHelper有写，但是AutoPlayRecyclerView里面私有了，木有提供出来。

**Comment by leochuan** [comment]
嗯，下个版本暴露一下，我在看另外一个问题，可能下一次更新还有段时间，你比较着急的话可以先实现下自己的`AutoPlayRecyclerView`。

**Comment by leochuan** [comment]
好了，`2.0.13`把`play` 和 `pause`暴露了
