### ISSUE TITLE
Problem in download 2.0.17 version

### ISSUE THREAD

**Issue by landarskiy** [leochuan/ViewPagerLayoutManager#55]
After update library version in gradle all classes disappear (probably aar packaging problems). Upload library into jcenter again please.

**Comment by leochuan** [comment]
Try to remove `~/.gradle/caches/modules-2/files-2.1/rouchuan.viewpagerlayoutmanager/viewpagerlayoutmanager/2.0.17` and re sync.

**Comment by kirich1409** [comment]
I tried  to delete artifacts cache and this help.
