### ISSUE TITLE
就按demo中的写法 出现崩溃

### ISSUE THREAD

**Issue by pjh520** [leochuan/ViewPagerLayoutManager#56]
![1](https://user-images.githubusercontent.com/12854050/39097579-ca5ece9c-4690-11e8-8b6f-851ec3e7de15.png)

![2](https://user-images.githubusercontent.com/12854050/39097582-cd3fb11c-4690-11e8-980f-e85be8eb5bdf.png)

**Comment by leochuan** [comment]
@pjh520 打开就崩吗？还是有什么操作之后才崩？

**Comment by pengjunhong** [comment]
@leochuan 我大概知道原因 你把列表item的宽度设置小点  这个问题就是必现的咯

**Comment by leochuan** [comment]
@pengjunhong 好像不是这个原因。。我设成1dp还是没有崩

**Comment by pengjunhong** [comment]
@leochuan忘了说  CarouselLayoutActivity这个activity会崩溃

**Comment by leochuan** [comment]
@pengjunhong 怎么操作会导致崩溃知道嘛？？

**Comment by pengjunhong** [comment]
@leochuan 进去就崩溃了然后就报那个view为空指针

**Comment by leochuan** [comment]
@pengjunhong 你机型和android版本是什么？

**Comment by pengjunhong** [comment]
@leochuan 如果你那边重现不了 我可以把 我这边将你的demo 给你 你试下 那个activity会不会崩溃

**Comment by leochuan** [comment]
好的，378534547这是我qq

**Comment by leochuan** [comment]
@pjh520 你是不是把itemSpace的大小和view的大小设成一样了

**Comment by pengjunhong** [comment]
@leochuan 看代码是的 就设置了那个地方

**Comment by leochuan** [comment]
试下 `2.0.18` 应该是`itemSpace`和`item`的宽度大小相同导致的问题，我做了下处理，现在应该是可以了，然后对于`CarouselLayoutManager` `itemSpace`是往里面挤的，所以当`itemSpace`和`item`的宽度相同时，所有`item`都会重叠。

**Comment by pengjunhong** [comment]
@leochuan 可以了

**Comment by djnotes** [comment]
Would you please explain what itemSpace is? I see no effect and difference when I change its value. Have been searching in code, but didn't find an explanation.
