### ISSUE TITLE
布局错位

### ISSUE THREAD

**Issue by ma-jian** [leochuan/ViewPagerLayoutManager#57]
使用CarouselLayoutManager 横向滚动，屏幕显示多个item时。 刷新数据 item会错位到左上角。（manager 添加了缩放功能，类似于ScaleLayoutManager）

**Comment by leochuan** [comment]
@ma-jian 添加了缩放功能？？怎么添加的？

**Comment by ma-jian** [comment]
就是直接把ScaleLayoutManager 的缩放代码拷过来了。
    @Override
    protected void setItemViewProperty(View itemView, float targetOffset) {
        float scale = calculateScale(targetOffset + mSpaceMain);
        itemView.setScaleX(scale);
        itemView.setScaleY(scale);
        final float alpha = calAlpha(targetOffset);
        itemView.setAlpha(alpha);
        requestLayout();
        if (itemViewPropertyListener != null) {
            itemViewPropertyListener.ItemViewProperty(itemView, targetOffset);
        }
    }

    private float calAlpha(float targetOffset) {
        final float offset = Math.abs(targetOffset);
        float alpha = (minAlpha - maxAlpha) / mInterval * offset + maxAlpha;
        if (offset >= mInterval) alpha = minAlpha;
        return alpha;
    }

    @Override
    protected float getDistanceRatio() {
        if (moveSpeed == 0) return Float.MAX_VALUE;
        return 1 / moveSpeed;
    }

    @Override
    protected float setViewElevation(View itemView, float targetOffset) {
        return itemView.getScaleX() * 5;
    }

    private float calculateScale(float x) {
        float deltaX = Math.abs(x - mSpaceMain);
        if (deltaX - mDecoratedMeasurement > 0) deltaX = mDecoratedMeasurement;
        return 1f - deltaX / mDecoratedMeasurement * (1f - minScale);
    }

**Comment by leochuan** [comment]
@ma-jian 这个我跑了没有问题，你能先缩小一下问题的范围吗？比如用没修改过的`CarouselLayoutManager`看看 问题是否依然存在，诸如此类

**Comment by leochuan** [comment]
@ma-jian 如果可以的话，你抽一个简单的demo发给我也可以，这样我比较方便定位问题

**Comment by ma-jian** [comment]
我先排查下是不是自己布局的问题。之前说错了是透明度。

**Comment by ma-jian** [comment]
问题找到了 是我这边布局写的有问题
