### ISSUE TITLE
滑动速度快的话，页卡的滚动速度会变得飞快。

### ISSUE THREAD

**Issue by pdog18** [leochuan/ViewPagerLayoutManager#64]
如果通过`setMoveSpeed` 设置一个较小的值，那么会导致卡片很难滑动 ，（例如demo中滚动速度设置为`0.2f`），卡片非常难滑动。如果一个较大的值（例如 4），那么轻轻一划则会突然过去很多。

我能想到是在某个地方，对导致高于某个快速滑动的值做个限制，不要突破一个设定的值，这样不管滑动多少快也不会出现飞一样的速度。

同时因为发现`setMoveSpeed`这个方法的确会对速度进行影响，所以我就从这个`moveSpeed`变量下手。

1. 查看发现`getDistanceRatio()` 使用了`moveSpeed`变量，这个方法貌似是获得滑动距离比例的，看起来会将`fling`的距离乘以这个系数。
2. `ViewPagerLayoutManager#scrollBy` 中使用到了`getDistanceRatio()`方法。
3.  在这里修改了`scrollBy`的传入参数`dy`，
```
      if (dy > 150) {
            dy = 150;
        } else if (dy < -150) {
            dy = -150;
        }
```
发现滑动不会飞起来了。但是滑动速度快的效果会很奇怪。

了解了一下这里用的是 `RecyclerView`的`fling`方法，于是我继承了`RecyclerView`然后重写`fling`
```
 @Override
    public boolean fling(int velocityX, int velocityY) {
        Log.e(TAG, String.valueOf(velocityX));

        if (velocityX > 5000) {
            velocityX = 5000;
        } else if (velocityX < -5000) {
            velocityX = -5000;
        }
        return super.fling(velocityX, (int) (velocityY * 0.2f));
    }
```

这样即使滑动速度超级快也不会让卡片飞一样的滑动了（滑出幻影..）。
看了`fling`的源码感觉可以通过修改`ViewFlinger` 中的`mScroller`的`sQuinticInterpolator`来对速度做控制。

**Comment by leochuan** [comment]
滚动速度什么的，即使滑的飞快，库里也不做限制了吧，这个放外面就好了
