### ISSUE TITLE
如何设置SnapView效果不居中呢？

### ISSUE THREAD

**Issue by lrannn** [leochuan/ViewPagerLayoutManager#69]
我们设计图上的效果是左对齐的。大神的代码我看的也有点吃力，想知道在哪一块改呢？主要我想保留的是无线滚动的功能，所以想在这个基础上改一哈。

**Comment by leochuan** [comment]
继承一下你需要的`LayoutManager`重写`setUp`方法，加一句`mSpaceMain = 0;`

**Comment by lrannn** [comment]
谢谢大神，我也会再深入研究一下的。感谢您的回复，thanks for your sharing!

**Comment by CeciliaKasumi** [comment]
如何去掉两边多余的距离呢？添加mSpaceMain = 0后多余的距离就都跑到最后那边去了
