### ISSUE TITLE
无限循环

### ISSUE THREAD

**Issue by MrShui** [leochuan/ViewPagerLayoutManager#7]
大神，请问实现无限循环有什么思路吗，我们这边有这个需求~ ~

**Comment by leochuan** [comment]
@MrShui 目前你要自己实现的话有两种方式，跟viewpager一样，一种是adapter获取时count+2, 然后比如你有4个数据, 你adapter获取数量时返回6。然后这样排列(为了说明方便我用数组表示)a = [0,1,2,3,0,1], 当滑动到a[0]时，设置位置到a[4]，滑动到a[5]时设置位置到a[1]。但recyclerview毕竟不像viewpager是一页页滚动的，所以这个方案不是很完美。还有一种是把count设为无穷大，然后获取位置时拿count对你真正的数据数量进行取余，但是我内部计算的时候其实会用到这个count，所以你不能把他设置成Integer.Max，只能取另一个很大的数。

虽然之后有空了我应该会加上无限滚动的支持，但我还是希望他被当作一个recyclerview来使用，设计之初也是这么考虑的。因为viewpager本身也可以通过transform来实现这些效果。你可以了解一下，就目前来说我觉得使用viewpager，并通过重写transfrom来实现你需要的效果，然后选取我上面说的任意一种方案实现无限滚动是一个更为完美的方案。

**Comment by MrShui** [comment]
谢谢回复！
实现无限循环的第一种方式count+2的那个会在滑到最后一个动画生硬吧。第二种方式倒是一直有用到。
之所以不用viewpager是因为，viewpager的点击事件之前发现是错乱的，也没有找到原因，所以就想着用recycleview试试。

**Comment by leochuan** [comment]
@MrShui 现在支持无限滚动了，不需要对adapter进行处理，你可以试一下新的代码
