### ISSUE TITLE
怎么能看到两个 条目滚动

### ISSUE THREAD

**Issue by to686312** [leochuan/ViewPagerLayoutManager#9]
![- 1 1](https://user-images.githubusercontent.com/15982492/27323093-f8ccc14e-55d2-11e7-9aef-fc9e9fdde45f.jpg)
  这样的效果  用你这个可以实现吗

**Comment by leochuan** [comment]
@to686312 你拉下新的代码，看我新增的ElevateLayoutManager,不过因为这个效果需要改变elevation，要求api21。你要在api21之前实现这种效果的话，可能需要将你的顶层布局使用CardView，然后仿照我的ElevateLayoutManager重新写一个，并把itemView强转成CardView

**Comment by to686312** [comment]
好的   谢谢大神   我去试试
